export const capitals = [
  { id: 1, name: "Abakaliki", color: "#4D7C0F", image: "" },
  { id: 2, name: "Ado-Ekiti", color: "#A93226", image: "" },
  { id: 3, name: "Akure", color: "#F97B22", image: "" },
  { id: 4, name: "Asaba", color: "#2E4F4F", image: "" },
  { id: 5, name: "Awka", color: "#0A9396", image: "" },
  { id: 6, name: "Bauchi", color: "#E9C46A", image: "" },
  { id: 7, name: "Benin City", color: "#2A4495", image: "" },
  { id: 8, name: "Calabar", color: "#E76F51", image: "" },
  { id: 9, name: "Damaturu", color: "#D62828", image: "" },
  { id: 10, name: "Dutse", color: "#023E8A", image: "" },
  { id: 11, name: "Enugu", color: "#6B9080", image: "" },
  { id: 12, name: "FCT", color: "#8FE3CF", image: "" },
  { id: 13, name: "Gombe", color: "#8FE3CF", image: "" },
  { id: 14, name: "Gusau", color: "#F4D160", image: "" },
  { id: 15, name: "Ibadan", color: "#720E07", image: "" },
  { id: 16, name: "Ikeja", color: "#EF4444", image: "" },
  { id: 17, name: "Ilorin", color: "#D6D5B7", image: "" },
  { id: 18, name: "Jalingo", color: "#3F497F", image: "" },
  { id: 19, name: "Jos", color: "#7A9E9F", image: "" },
  { id: 20, name: "Kaduna", color: "#F2B138", image: "" },
  { id: 21, name: "Kano", color: "#4D96FF", image: "" },
  { id: 22, name: "Katsina", color: "#8D5524", image: "" },
  { id: 23, name: "Lafia", color: "#F9D949", image: "" },
  { id: 24, name: "Lokoja", color: "#E96479", image: "" },
  { id: 25, name: "Makurdi", color: "#D0F0C0", image: "" },
  { id: 26, name: "Minna", color: "#4CC9F0", image: "" },
  { id: 27, name: "Oshogbo", color: "#F72585", image: "" },
  { id: 28, name: "Owerri", color: "#7FB77E", image: "" },
  { id: 29, name: "Port Harcourt", color: "#ECC30B", image: "" },
  { id: 30, name: "Umuahia", color: "#A8E6CF", image: "" }, //1
  { id: 31, name: "Uyo", color: "#FF6D00", image: "" }, //3
  { id: 32, name: "Yenagoa", color: "#8D8DAA", image: "" },
  { id: 33, name: "Yola", color: "#3D2C8D", image: "" }, //2
  { id: 34, name: "Sokoto", color: "#B0DAFF", image: "" },
  { id: 35, name: "Zaria", color: "#FFA900", image: "" },
];
