export const capitals = [
    { name: "Abakaliki", color: "#4D7C0F", image: "" },
    { name: "Ado-Ekiti", color: "#A93226", image: "" },
    { name: "Akure", color: "#F97B22", image: "" },
    { name: "Asaba", color: "#2E4F4F", image: "" },
    { name: "Awka", color: "#0A9396", image: "" },
    { name: "Bauchi", color: "#E9C46A", image: "" },
    { name: "Benin City", color: "#2A4495", image: "" },
    { name: "Calabar", color: "#E76F51", image: "" },
    { name: "Damaturu", color: "#D62828", image: "" },
    { name: "Dutse", color: "#023E8A", image: "" },
    { name: "Enugu", color: "#6B9080", image: "" },
    { name: "Gombe", color: "#8FE3CF", image: "" },
    { name: "Gusau", color: "#F4D160", image: "" },
    { name: "Ibadan", color: "#720E07", image: "" },
    { name: "Ikeja", color: "#EF4444", image: "" },
    { name: "Ilorin", color: "#D6D5B7", image: "" },
    { name: "Jalingo", color: "#3F497F", image: "" },
    { name: "Jos", color: "#7A9E9F", image: "" },
    { name: "Kaduna", color: "#F2B138", image: "" },
    { name: "Kano", color: "#4D96FF", image: "" },
    { name: "Katsina", color: "#8D5524", image: "" },
    { name: "Lafia", color: "#F9D949", image: "" },
    { name: "Lokoja", color: "#E96479", image: "" },
    { name: "Makurdi", color: "#D0F0C0", image: "" },
    { name: "Minna", color: "#4CC9F0", image: "" },
    { name: "Oshogbo", color: "#F72585", image: "" },
    { name: "Owerri", color: "#7FB77E", image: "" },
    { name: "Port Harcourt", color: "#ECC30B", image: "" },
    { name: "Umuahia", color: "#A8E6CF", image: "" },
    { name: "Uyo", color: "#FF6D00", image: "" },
    { name: "Yenagoa", color: "#8D8DAA", image: "" },
    { name: "Yola", color: "#3D2C8D", image: "" },
    { name: "Sokoto", color: "#B0DAFF", image: "" },
    { name: "Zaria", color: "#FFA900", image: "" }
];