export const industries = [
  { id: "agriculture", label: "Agriculture" },
  { id: "manufacturing", label: "Manufacturing" },
  { id: "services", label: "Services" },
  { id: "technology", label: "Technology" },
  { id: "healthcare", label: "Healthcare" },
  { id: "energy", label: "Energy" },
  { id: "construction", label: "Construction" },
  { id: "retail", label: "Retail" },
  { id: "education", label: "Education" },
  { id: "finance", label: "Finance" },
  { id: "transportation", label: "Transportation" },
  { id: "telecommunications", label: "Telecommunications" },
  { id: "real_estate", label: "Real Estate" },
  { id: "food_and_beverage", label: "Food & Beverage" },
  { id: "media", label: "Media" },
  { id: "tourism", label: "Tourism" },
  { id: "entertainment", label: "Entertainment" },
  { id: "public_sector", label: "Public Sector" },
];
