export const industries = [
  { id: "agriculture", name: "Agriculture" },
  { id: "manufacturing", name: "Manufacturing" },
  { id: "services", name: "Services" },
  { id: "technology", name: "Technology" },
  { id: "healthcare", name: "Healthcare" },
  { id: "energy", name: "Energy" },
  { id: "construction", name: "Construction" },
  { id: "retail", name: "Retail" },
  { id: "education", name: "Education" },
  { id: "finance", name: "Finance" },
  { id: "transportation", name: "Transportation" },
  { id: "telecommunications", name: "Telecommunications" },
  { id: "real_estate", name: "Real Estate" },
  { id: "food_and_beverage", name: "Food & Beverage" },
  { id: "media", name: "Media" },
  { id: "tourism", name: "Tourism" },
  { id: "entertainment", name: "Entertainment" },
  { id: "public_sector", name: "Public Sector" },
];
