export const job_roles = [
  "Manager",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Mobile Developer",
  "DevOps Engineer",
  "Designer",
  "UI Designer",
  "UX Designer",
  "Visual Designer",
  "Interaction Designer",
  "Motion Designer",
  "Data Analyst",
  "Cloud Architect",
  "Network Engineer",
  "Security Analyst",
  "Database Administrator",
  "Technical Writer",
  "AI/Machine Learning Engineer",
  "Blockchain Developer",
  "IoT Developer",
  "AR/VR Developer",
  "Game Developer",
  "Sales Representative",
  "Marketing Specialist",
  "Customer Service Representative",
  "Human Resources Manager",
  "Financial Analyst",
  "Project Manager",
  "Data Scientist",
  "Product Manager",
  "Quality Assurance Tester",
  "Systems Administrator",
  "Business Analyst",
  "Content Writer",
  "Graphic Designer",
  "Software Engineer",
  "IT Support Specialist",
  "Operations Manager",
  "Account Executive",
];
